#PBS -N blastn_2
#PBS -V
#PBS -A tyjames_flux
#PBS -l qos=flux
#PBS -q flux
#PBS -l nodes=1:ppn=3,mem=6gb,walltime=200:00:00
#PBS -M amsesk@umich.edu
#PBS -m abe
#PBS -j oe

### Your commands go below:

module load ncbi-blast
cd /scratch/tyjames_flux/amsesk/rhizopus/discard/blastn

blastn -query ../contig.fastas/XY01865_contigs.clip.500.fasta -outfmt "6 qseqid sseqid pident qlen length mismatch gapope evalue bitscore staxids" -num_threads 3 -out XY01865_blastn.out -max_target_seqs 1 -db nt
blastn -query ../contig.fastas/XY01874_contigs.clip.500.fasta -outfmt "6 qseqid sseqid pident qlen length mismatch gapope evalue bitscore staxids" -num_threads 3 -out XY01874_blastn.out -max_target_seqs 1 -db nt
blastn -query ../contig.fastas/XY01875_contigs.clip.500.fasta -outfmt "6 qseqid sseqid pident qlen length mismatch gapope evalue bitscore staxids" -num_threads 3 -out XY01875_blastn.out -max_target_seqs 1 -db nt
